name: 📦 Build
run-name: 📦 Build triggered
on: push
jobs:
  build:
    name: Istop build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      # Instala o Node.JS
      - name: Install node.js
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"

      # Instala as dependências da aplicação
      - name: Install app dependencies
        run: yarn

      # Faz o build da aplicação
      - name: Build app
        run: yarn build

      # Configura as credenciais da AWS se o ambiente for master
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1

      # Copia o arquivo zipado para o bucket de artefatos
      - name: Copy files to artifact bucket
        run: aws s3 sync ./public s3://istop-web
